"""scheduled reminders

Revision ID: 35e1fd34e1ae
Revises: fa9e40257327
Create Date: 2026-09-17 17:38:35.264843

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35e1fd34e1ae"
down_revision: str | None = "fa9e40257327"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_reminders",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("occurrence_at", sa.DateTime(), nullable=False),
        sa.Column("remind_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("day_before", "hour_before", "occurrence", name="reminder_kind"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "sent", "cancelled", "failed", name="reminder_status"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "task_id", "occurrence_at", "kind", name="uq_reminder_task_occurrence_kind"
        ),
    )
    op.create_index(
        op.f("ix_scheduled_reminders_remind_at"), "scheduled_reminders", ["remind_at"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_reminders_task_id"), "scheduled_reminders", ["task_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheduled_reminders_task_id"), table_name="scheduled_reminders")
    op.drop_index(op.f("ix_scheduled_reminders_remind_at"), table_name="scheduled_reminders")
    op.drop_table("scheduled_reminders")
    # ### end Alembic commands ###
