"""task completions

Revision ID: fe38ae2bfeeb
Revises: 8925399efd7d
Create Date: 2026-09-17 16:56:13.359392

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe38ae2bfeeb"
down_revision: str | None = "8925399efd7d"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_completions",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("occurrence_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("skipped", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_completions_task_id"), "task_completions", ["task_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_completions_task_id"), table_name="task_completions")
    op.drop_table("task_completions")
    # ### end Alembic commands ###
